# Generated by Django 5.0.1 on 2024-02-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='email_id',
        ),
    ]
