# Generated by Django 5.0.1 on 2024-03-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_remove_emp_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department_id', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('working', models.BooleanField(default=True)),
            ],
        ),
    ]
