# Generated by Django 5.0.1 on 2024-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_holder_name', models.CharField(max_length=200)),
                ('salary_holder_id', models.CharField(max_length=200)),
                ('salary_account_no', models.CharField(max_length=200)),
                ('salary_date', models.CharField(max_length=200)),
                ('salary_amount', models.CharField(max_length=200)),
            ],
        ),
    ]
