# Generated by Django 5.0.1 on 2024-03-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='salary_account_no',
            new_name='account_no',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='salary_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='salary_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='salary_holder_id',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='salary_holder_name',
            new_name='salary_id',
        ),
    ]
