# Generated by Django 5.0.1 on 2024-03-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_rename_salary_account_no_salary_account_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('leaving_id', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
                ('apruval', models.BooleanField(default=True)),
            ],
        ),
    ]
